/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.muraviev.java.xml_1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

}
